### ISSUE TITLE
Rename project to aos-web-lft-selenium

### ISSUE THREAD

**Issue by jhrabi** [panama69/Lft4Se#8]
In keeping with our previous test project names, would like to rename this project to aos-web-lft-selenium

**Comment by panama69** [comment]
how about naming it 'aos-web-lft4se'?
i kind of would like to keep the short acronym in it as there are references on the support site of [LeanFT for Selenium](https://admhelp.microfocus.com/leanft/en/14.50/HelpCenter/Content/HowTo/Sel_LeanFT4SelT.htm) and I think it is easier for the field and others to make this connection with the capability the script is attempting to portray.

**Comment by jhrabi** [comment]
Works for me

Jason Hrabi
ADM Presales Technical Consultant
Micro Focus

(P)+1 647.238.3234
jason.hrabi@microfocus.com
________________________________

**Comment by jhrabi** [comment]
Works for me

**Comment by panama69** [comment]
renamed.
